version: "3.8"

networks:
  wanderly-network:
    name: wanderly-network
    driver: bridge

volumes:
  wanderly-storage:
    name: wanderly-storage

services:
  frontend:
    image: avi004/wanderly-frontend:latest
    container_name: wanderly-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - wanderly-network

  backend:
    image: avi004/wanderly-backend:latest
    container_name: wanderly-backend
    restart: always
    environment:
      MONGO_URI: mongodb://mongodb:27017/wanderly
      NODE_ENV: production
    depends_on:
      - mongodb
    networks:
      - wanderly-network

  mongodb:
    image: mongo:6
    container_name: wanderly-mongodb
    restart: always
    volumes:
      - wanderly-storage:/data/db
    networks:
      - wanderly-network

  nginx:
    image: avi004/wanderly-nginx:latest
    container_name: wanderly-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - wanderly-network
